/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      boxShadow: {
        e3: "0px 1px 1px -0.5px var(--elevation-shadow), 0px 3px 3px -1.5px var(--elevation-shadow), 0px 20px 20px -12px var(--elevation-shadow)",
        card: "var(--shadow-card)",
      },
      fontFamily: {
        sans: [
          "Poppins",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        // brand object removed
        surface: {
          "info-alpha": "rgba(6, 177, 241, 0.12)",
          "primary-alpha": "rgba(121, 107, 255, 0.12)",
          "success-med-em": "var(--surface-success-med-em)",
          "success-low-em": "var(--surface-success-low-em)",
          "info-low-em": "var(--surface-info-low-em)",
          "info-med-em": "var(--surface-info-med-em)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        /* Generated from Figma */
        neutral600: "var(--neutral-600)",
        neutral100: "var(--neutral-100)",
        white100: "var(--white-100)",
        textHighEm: "var(--text-high-em)",
        surfacePrimaryHighEm: "var(--surface-primary-high-em)",
        surfacePrimaryBaseEm: "var(--surface-primary-base-em)",
        textMedEm: "var(--text-med-em)",
        textLowEm: "var(--text-low-em)",
        textSubText: "var(--text-sub-text)",
        textMainText: "var(--text-main-text)",
        backgroundWhite: "var(--background-white)",
        surfacePrimaryMedEm: "var(--surface-primary-med-em)",
        iconOffWhite: "var(--icon-off-white)",
        paletteTextRegular: "var(--palette-text-regular)",
        paper: "var(--paper)",
        outlineSuccessHighEm: "var(--outline-success-high-em)",
        outlinePrimaryButtonTop: "var(--outline-primary-button-top)",
        outlinePrimaryButtonBottom: "var(--outline-primary-button-bottom)",
        elevationShadow: "var(--elevation-shadow)",
        colorWhite12: "var(--color-white-12)",
        colorWhite3: "var(--color-white-3)",

        colorBackgroundSubtle: "var(--color-background-subtle)",
        gray200: "var(--gray-200)",
        colorBorderDefault: "var(--color-border-default)",
        textPrimary: "var(--text-primary)",
        textSecondary: "var(--text-secondary)",
        warningMain: "var(--warning-main)",
        warningOMain: "var(--warning-o-main)",
        textWarningHighEm: "var(--text-warning-high-em)",
        outlineWarningBaseEmAlpha: "var(--outline-warning-base-em-alpha)",
        surfaceSpecialLightS3DarkS4: "var(--surface-special-light-s3-dark-s4)",
        surfaceSpecialBlurBaseLight: "var(--surface-special-blur-base-light)",
        textDisabled: "var(--text-disabled)",
        actionHover: "var(--action-hover)",
        surfaceSpecialSecondaryAlphaBase:
          "var(--surface-special-secondary-alpha-base)",
        outlineSecondaryButtonBottom: "var(--outline-secondary-button-bottom)",
        outlineSecondaryButtonTop: "var(--outline-secondary-button-top)",
        outlineMedEm: "var(--outline-med-em)",
        outlineBaseEm: "var(--outline-base-em)",
        outlineLowEm: "rgba(0, 0, 0, 0.06)",
        surfaceS0: "var(--surface-s0)",
        surfaceSpecialLightS0DarkS1: "var(--surface-special-light-s0-dark-s1)",
        outlineSecondary: "transparent",
        outlinePrimary: "transparent",
        surfaceSuccessBaseEmAlpha: "var(--surface-success-base-em-alpha)",
        surfaceDangerBaseEmAlpha: "var(--surface-danger-base-em-alpha)",
        surfaceInfoBaseEmAlpha: "var(--surface-info-base-em-alpha)",
        outlineInfoHighEm: "var(--outline-info-high-em)",
        textPrimaryHighEm: "var(--text-primary-high-em)",
        universal: {
          "text-regular": "var(--universal-palette-text-regular)",
          "border-white": "var(--universal-palette-border-white)",
        },
        surfaceS1: "var(--surface-s1)",
        textBaseEm: "var(--text-base-em)",
        surfaceSpecialLightS0DarkS2: "var(--surface-special-light-s0-dark-s2)",
        gray: {
          2: "var(--gray-2)",
          light: "var(--light-gray)",
        },
        surfaceInverseWhite: "var(--surface-inverse-white)",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xxl: "var(--radius-xxl)",
        xs: "var(--radius-xs)",
        "comp-md": "var(--radius-md)", // Renamed to comp-md to avoid conflict? Or keep md?
        "comp-lg": "var(--radius-comp-lg)",
        // User asked for radius_0.
        0: "var(--radius-0)",
        "comp-sm": "var(--radius-comp-sm)",
        "big-comp-sm": "var(--radius-big-component-sm)",
        "figma-md": "var(--radius-figma-md)",
        "big-comp-md": "var(--radius-big-comp-md)",
      },
      fontSize: {
        "body-1": ["var(--font-size-body-1)", "var(--line-height-body-1)"],
        "body-2": ["var(--font-size-body-2)", "var(--line-height-body-2)"],
        "title-2": ["var(--font-size-title-2)", "var(--line-height-title-2)"],
        "heading-2": [
          "var(--font-size-heading-2)",
          "var(--line-height-heading-2)",
        ],
        sm: "var(--font-size-sm)",

        sm: "var(--font-size-sm)",
      },
      fontWeight: {
        semibold: "var(--font-weight-semibold)",
        medium: "var(--font-weight-medium)",
        regular: "var(--font-weight-regular)",
      },
      spacing: {
        xxs: "var(--spacing-xxs)",
        md: "var(--spacing-md)",
        xl: "var(--spacing-xl)",
        "3xl": "var(--spacing-3xl)",
        "5xl": "var(--spacing-5xl)",
        "7xl": "var(--spacing-7xl)",
        "7xl": "var(--spacing-7xl)", // 24
        "card-header": "var(--misc-card-header)",
        "figma-xxs": "var(--space-figma-xxs)",
        "figma-xs": "var(--space-figma-xs)",
        "figma-md": "var(--space-figma-md)",
        "figma-4xl": "var(--space-figma-4xl)",
        "figma-10xl": "var(--space-figma-10xl)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
